### ISSUE TITLE
mdx doesn't appear to work. 

### ISSUE THREAD

**Issue by craig-mulligan** [jamesknelson/sitepack-react-starter-kit#1]
Hi 👋 

I tried adding adding the example from http://dump.jamesknelson.com/mdxc-playground.html to /about.md. It return the markup but the event handlers didn't seem to be attached. Editing the input doesn't trigger anything. 

I'm still figuring out how mdx works 😆 , so not sure sure how to debug atm.

**Comment by jamesknelson** [comment]
The `value` and `onChange` handlers are actually playground-specific things. You could pass them into your generated component, but you'd have to handle them yourself with component state in the component that consumes your document.

Does this make sense? Might not be the clearest explanation...

**Comment by craig-mulligan** [comment]
@jamesknelson Ah yes that makes sense. I was blindly copy'n pasting to test :)
